#!/bin/sh
status=$(playerctl -p spotify status 2> /dev/null)
artist=$(playerctl -p spotify metadata artist 2> /dev/null)
title=$(playerctl -p spotify metadata title 2> /dev/null)

if [ "$status" = "Playing" ]; then
	printf ' '
elif [ "$status" = "Paused" ]; then
	printf ' '
fi

if [ ! -z "$artist" ] || [ ! -z "$title" ]; then
	printf ' %s - %s ' "$artist" "$title"
fi

