#!/bin/bash

wid=`xdotool search --classname gotop | head -n 1`
if [ -z "$wid" ]; then
   /usr/bin/urxvt -name gotop -e gotop
   wid=$(xdotool search --classname gotop | head -n 1)
   xdotool windowfocus $wid
else
    if [ -z "$(xdotool search --onlyvisible --classname urxvtq 2>/dev/null | head -n 1)" ];     then
        xdotool windowmap $wid
        xdotool windowfocus $wid
    else
        xdotool windowunmap $wid
    fi
fi
