#!/bin/bash
# Inspired by https://gist.github.com/Tadly/0741821d3694deaec1ee454a95c591fa
# emoji list that's used was made with this
if [ -n "$1" ]
then
  # Arguments have been passed so copy the value
  echo -n "${1:0:1}" | xsel -i -b
else
  # Generate list
  cat ~/.cache/emojis.txt | grep -v '#' | grep -v '^[[:space:]]*$'
fi
