#!/bin/sh
# Modified from https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/isrunning-service/isrunning-service.sh
 
UNIT="openvpn-client@fra_vpn.service"
 
if [ "$(systemctl is-active "$UNIT")" = "active" ]; then
        sudo /usr/bin/systemctl stop openvpn-client@fra_vpn.service
else
        sudo /usr/bin/systemctl start openvpn-client@fra_vpn.service
fi


